about/urls.py
# from main import views
# from django.contrib import admin
from django.urls import path

from about import views

app_name = 'about'

urlpatterns = [
    path('about/', views.about, name='about'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path, include
from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path('catalog/', include('products.urls', namespace="catalog")),
    path("about/", include("about.urls", namespace="about")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from main import views
# from django.contrib import admin
from django.urls import path

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
]

products/urls.py
from django.urls import path
from products import views

app_name = 'products'

urlpatterns = [
    path('', views.catalog, name='index'),
    path('product/', views.product, name='product'),
]

about/models.py
from django.db import models

# Create your models here.

contacts/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models

class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True)

    class Meta:
        db_table = 'category'
    
    def __str__(self):
        return self.name



class Products(models.Model):
    name = models.CharField(max_length=150, unique=True)
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='products_images', blank=True, null=True)
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2)
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE)
    
    class Meta:
        db_table = "product"
        
    def __str__(self):
        return f'{self.name} Amount - {self.quantity}'
    
    def display_id(self):
        return f'{self.id:05}'
    
    
    def sell_price(self):
        if self.discount:
            return round(self.price - self.price*self.discount/100, 2)
        
        return self.price

about/views.py
from django.shortcuts import render
from django.http import HttpResponse


def about(request):
    context = {
        "title": "Sunline - about",
        "content": "About",
        "text_on_page": "why this store is so awesome and needfull",
    }
    return render(request, "about/about.html", context)

contacts/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render
from django.http import HttpResponse

from products.models import Categories


def index(request):

    context = {
        'title': 'Home',
        'content': 'This is a main page',
    }

    return render(request, 'main/index.html', context)

products/views.py
from django.shortcuts import render

from products.models import Products



def catalog(request):
    products = Products.objects.all()
    context = {
        "products": products
    }
    return render(request, 'products/catalog.html', context)


def product(request):
    return render(request, 'products/product.html')

about/templates/about/about.html
{% extends "main/base.html" %}
{% load static %}



{% block block_content %}

    <p>this is a blog page</p>

{% endblock %}

main/templates/main/base.html
{% load static %}

{% load producttags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link rel="icon" href="{% static 'deps/images/favicon.ico' %}" type="image/x-icon">
    <link rel="stylesheet" href=" {% static 'deps/css/reset.css' %} " />
    <link rel="stylesheet" href=" {% static 'deps/css/style.css' %} " />
  </head>

  <body>
    <div class="wrapper">
      <header class="header">
        <div class="container">
          <div class="header__inner">
            <a class="logo" href=" {% url "main:index" %} "><img src="" alt="" /></a>
            <nav class="menu">
              <ul class="menu__list">
                <li class="menu__list-item">
                  <a class="menu__list-link" href=" {% url "main:index" %}">Home</a>
                </li>
                <li class="menu__list-item menu__list-item--dropdown">
                  <a class="menu__list-link menu__list-link--dropdown__products" href="#">
                      Products
                      <svg width="22px" height="22px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path fill-rule="evenodd" clip-rule="evenodd" d="M12.7071 14.7071C12.3166 15.0976 11.6834 15.0976 11.2929 14.7071L6.29289 9.70711C5.90237 9.31658 5.90237 8.68342 6.29289 8.29289C6.68342 7.90237 7.31658 7.90237 7.70711 8.29289L12 12.5858L16.2929 8.29289C16.6834 7.90237 17.3166 7.90237 17.7071 8.29289C18.0976 8.68342 18.0976 9.31658 17.7071 9.70711L12.7071 14.7071Z" fill="#000"/>
                      </svg>
                  </a>
                  <ul class="submenu">
                    {% tag_categories as categories %}
                    {% for category in categories %}
                    <li class="submenu__item">
                        <a class="submenu__link" href=" {% url "catalog:index"%} "> {{category.name}} </a>
                    </li>                                        
                    {% endfor %}
                </ul>
              </li>
                <li class="menu__list-item">
                  <a class="menu__list-link" href=" {% url "about:about" %} ">About</a>
                </li>
                <li class="menu__list-item">
                  <a class="menu__list-link" href=" {% url "about:about" %} ">Contacts</a>
                </li>
              </ul>
            </nav>
            <div class="user-nav">
              <form class="form" role="search" action="" method="get">
                <input class="form__input" role="search" type="search" placeholder="Search" aria-label="Search" name="q" />
                <button class="form__input-btn" type="submit"><img src=" {% static 'deps/images/icons/search.svg' %} " alt="" /></button>
              </form>
              <a href="#"><img src=" {% static 'deps/images/icons/cart.svg' %} " alt="" /></a>

                <li class="menu__list-item menu__list-item--dropdown">
                  <a class="menu__list-link menu__list-link--dropdown__user" href="">
                      <img src="{% static 'deps/images/icons/user.svg' %}" alt="">
                  </a>
                  <ul class="submenu">
                          <li class="submenu__item">
                              <a class="submenu__link" href="">Login</a>
                          </li>


              <li class="submenu__item"><a class="submenu__link" href="">Personal Account</a></li>
                  <li class="submenu__item"><a class="submenu__link" href="{% url "admin:index" %}">Admin Panel</a></li>
              <li class="submenu__item"><a class="submenu__link" href="">Logout</a></li>
          </li>
            </div>
          </div>
        </div>
      </header>

      <main class="main">
        {% block block_content %}
        {% endblock %}
      </main>

      <footer class="footer">
        <div class="footer__content">
          <div class="container">
            <div class="footer__inner">
              <div class="footer__info">
                <h6 class="footer__info-title">Contact Us</h6>
                <p class="footer__info-text">Keffiyeh poutine etsy, paleo cray put a bird on it microdosing schlitz you probably occupy</p>
                <a class="info-email" href="mailto:ouremailaddress@email.com">ouremailaddress@email.com</a>
                <form class="footer__form">
                  <input class="footer__form-input" type="email" placeholder="Subscribe by email" />
                  <button class="footer__form-button" type="submit">Send</button>
                </form>
              </div>
              <ul class="footer__social">
                <li class="footer__social-item">
                  <a class="footer__social-link footer__social-link--facebook" href="#">Facebook</a>
                </li>
                <li class="footer__social-item">
                  <a class="footer__social-link footer__social-link--instagram" href="#">Instagram</a>
                </li>
                <li class="footer__social-item">
                  <a class="footer__social-link footer__social-link--pinterest" href="#">Pinterest</a>
                </li>
                <li class="footer__social-item">
                  <a class="footer__social-link footer__social-link--whatsapp" href="#">WhatsApp</a>
                </li>
                <li class="footer__social-item">
                  <a class="footer__social-link footer__social-link--youtube" href="#">Youtube</a>
                </li>
              </ul>
              <nav class="footer__menu">
                <ul class="footer__menu-list">
                  <li class="footer__menu-item">
                    <a class="footer__menu-link" href="#">Delivery</a>
                  </li>
                  <li class="footer__menu-item">
                    <a class="footer__menu-link" href="#">FAQ</a>
                  </li>
                  <li class="footer__menu-item">
                    <a class="footer__menu-link" href="#">HELP</a>
                  </li>
                  <li class="footer__menu-item">
                    <a class="footer__menu-link" href="#">More About Us</a>
                  </li>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </footer>
    </div>

    <script src=" {% static 'js/main.js' %} "></script>
  </body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}



{% block block_content %}
  <main class="main">
    <p>this is a index page</p>
  </main>
{% endblock %}

products/templates/products/catalog.html
{% extends 'main/base.html' %}
{% load static %}


{% block block_content %}
<section class="top">
  <div class="top__container" style="background-image: url('');">
      <div class="container">
          <h2 class="top__title title">Shop page</h2>
          {% comment %} <div class="breadcrumbs">
              <ul class="breadcrumbs__list">
                  <li class="breadcrumbs__item">
                      <a class="breadcrumbs__link" href="#">
                          Home
                      </a>
                  </li>
                  <li class="breadcrumbs__item">
                      <a class="breadcrumbs__link" href="#">
                          Shop page
                      </a>
                  </li>
              </ul>
          </div> {% endcomment %}
      </div>
  </div>
</section>
  <section class="shop">
    <div class="container">
      <div class="shop__inner">
        <div class="shop__filters filter">
          <div class="filter__item">
            <form action="" method="get" class="" data-bs-theme="dark">
              <div class="">
                <input class="" type="checkbox" name="on_sale" id="flexCheckDefault" value="on" >
                <input type="hidden" name="q" value="" /> 
                <label class="" for="flexCheckDefault">Products on sale</label>
              </div>
              <button class="filter-btn" type="submit" class="">Apply</button>
            </form>
          </div>
          <div class="filter__item">
            <div class="">
              <form action="" method="get" class="" data-bs-theme="dark">
                <h5 class="filter__item-title">FILTER BY PRICE</h5>
                <div class="">
                  <input class="" type="radio" name="order_by" id="flexRadioDefault1" value="default"  />
                  <label class="" for="flexRadioDefault1">Default</label>
                </div>
                <div class="">
                  <input class="" type="radio" name="order_by" id="flexRadioDefault2" value="price" />
                  <label class="" for="flexRadioDefault2">From cheap to expensive</label>
                </div>
                <div class="">
                  <input class="" type="radio" name="order_by" id="flexRadioDefault3" value="-price" />
                  <label class="" for="flexRadioDefault3">From expensive to cheap</label>
                </div>
                <button class="filter-btn" type="submit" class="">Apply</button>
              </form>
            </div>
          </div>
            <div class="filter__item">
              <div class="">
                <form action="" method="get" class="" data-bs-theme="dark">
                  <h5 class="filter__item-title">FILTER BY TYPE</h5>
                  <div class="">
                    <input class="" type="radio" name="on_type" id="RadioDefault1" value="default"  />
                    <label class="" for="flexRadioDefault1">Default</label>
                  </div>
                  <div class="">
                    <input class="" type="radio" name="on_type" id="RadioDefault2" value="collars_harness" />
                    <label class="" for="flexRadioDefault2">Collars and Harness</label>
                  </div>
                  <div class="">
                    <input class="" type="radio" name="on_type" id="RadioDefault3" value="food" />
                    <label class="" for="flexRadioDefault3">Food</label>
                  </div>
                  <div class="">
                    <input class="" type="radio" name="on_type" id="RadioDefault4" value="clothes" />
                    <label class="" for="flexRadioDefault3">Clothes</label>
                  </div>
                  <div class="">
                    <input class="" type="radio" name="on_type" id="RadioDefault5" value="beds"  />
                    <label class="" for="flexRadioDefault3">Beds</label>
                  </div>
                  <div class="">
                    <input class="" type="radio" name="on_type" id="RadioDefault6" value="vitamins"  />
                    <label class="" for="flexRadioDefault3">Vitamins</label>
                  </div>
                  <div class="">
                    <input class="" type="radio" name="on_type" id="RadioDefault7" value="grooming"  />
                    <label class="" for="flexRadioDefault3">Grooming</label>
                  </div>
                  <div class="">
                    <input class="" type="radio" name="on_type" id="RadioDefault8" value="dry_food" />
                    <label class="" for="flexRadioDefault3">Dry Food</label>
                  </div>

                  
                  <button class="filter-btn" type="submit" class="">Apply</button>
                </form>
              </div>
          </div>



        </div>
        <div class="shop-content">
          <div class="shop-content__inner">
            {% comment %} <h3 class="">Search results for your query  </h3> {% endcomment %}
            {% comment %} product card {% endcomment %}
            {% for product in products %}
            <div class="product">
              <div class="product__image">
                <a href="">
                  <img class="product-item__images" src=" {{ product.image.url }} " alt=" " />
                </a>
              </div>
              <div class="product-item__wrapper-box">
                <div class="product-item__box">
                  <div class="product-item__info">
                    <h5 class="product__category"><a href="">{{ product.category }}</a></h5>
                    <div style="display: none;" class="">  </div>
                    <div class="product_id">id: <span> {{ product.display_id }} </span></div> 
                  </div>
                  <a href=""><h4 class="product__title"> 
                    {{ product.name }}
                  </h4>
                </a>
                <div class="product__price__container">
                  {% if product.discount %}
                    <div class="product__new-price">$ {{ product.sell_price }}</div>
                    <div class="product-item__old-price">$ {{ product.price }}</div>
                  {% else %}
                    <div class="product__new-price">$ {{ product.price }}</div>
                  {% endif %}
                </div>
                </div>
                <div class="product-item__content-box">
                  <div class="product__btns-container">

                      <a class="product__cart-btn btn add-to-cart" href="">Buy Now</a>
                      <a class="product__wishlist-btn btn add-to-wishlist" href="">
                      <?xml version="1.0" encoding="utf-8"?>
                      <svg width="28px" height="28px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                      <path d="M15.7 4C18.87 4 21 6.98 21 9.76C21 15.39 12.16 20 12 20C11.84 20 3 15.39 3 9.76C3 6.98 5.13 4 8.3 4C10.12 4 11.31 4.91 12 5.71C12.69 4.91 13.88 4 15.7 4Z" stroke="#fff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
                      </svg>
                      </a>
                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
              {% comment %} end product card {% endcomment %}
          </div>
        </div>
      </div>
      <div class="pagination">
        <a class="pagination__prev"
          href="#"> Previus
        </a>
        <ul class="pagination__list">
              <li class="pagination__item">
                <a class="pagination__link"></a>
              </li>
        </ul>
        <a class="pagination__next"
          href="#"> Next
        </a>
      </div>
    </div>
  </section>
{% endblock %}